### ISSUE TITLE
未知的错误

### ISSUE THREAD

**Issue by damemod** [MX233/AntiRecall#1]
2022-08-28 17:47:23 E/Bot.2636301776: java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageSyncEvent'
java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageSyncEvent'
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:103)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$1.invokeSuspend(EventDispatcher.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: 未找到异常处理器. 请继承 SimpleListenerHost 中的 handleException 方法, 或在构造 SimpleListenerHost 时提供 CoroutineExceptionHandler
------------
Cannot find exception handler from coroutineContext. 
Please extend SimpleListenerHost.handleException or provide a CoroutineExceptionHandler to the constructor of SimpleListenerHost
        at net.mamoe.mirai.event.SimpleListenerHost.handleException(JvmMethodListeners.kt:192)
        at net.mamoe.mirai.event.SimpleListenerHost$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
        at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:75)
        at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:125)
        at net.mamoe.mirai.internal.event.EventListeners.callListeners$mirai_core(EventListeners.kt:73)
        at net.mamoe.mirai.internal.event.EventListeners$callListeners$1.invokeSuspend(EventListeners.kt)
        ... 9 more
Caused by: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:91)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callFunction(JvmMethodListenersInternal.kt:1)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invokeSuspend(JvmMethodListenersInternal.kt:110)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invoke(JvmMethodListenersInternal.kt)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$8.invoke(JvmMethodListenersInternal.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
        ... 12 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:56)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:80)
        ... 26 more
Caused by: java.lang.IllegalArgumentException: Unsupported MessageEvent: net.mamoe.mirai.event.events.GroupMessageSyncEvent
        at net.mamoe.mirai.console.command.CommandSender$Companion.from(CommandSender.kt:258)
        at antiRecall-1.0.2.mirai.jar//top.cutestar.antiRecall.EventHost$MessageEventHost.onHandle(EventHost.kt:44)
        ... 35 more

**Comment by damemod** [comment]
另外闪照的发送不受权限的影响，也就是说任何群都能传递闪照信息发送到接受的对象

**Comment by Pmaru-top** [comment]
【未知的错误】不知道怎么回事，不影响使用的话可以先凑合着用

闪照转发权限问题已修复，可以下载[1.0.3](https://github.com/MX233/AntiRecall/releases/download/1.0.3/antiRecall-1.0.3.mirai.jar)版本使用

**Comment by damemod** [comment]
> 【未知的错误】不知道怎么回事，不影响使用的话可以先凑合着用
> 
> 闪照转发权限问题已修复，可以下载[1.0.3](https://github.com/MX233/AntiRecall/releases/download/1.0.3/antiRecall-1.0.3.mirai.jar)版本使用

会使mirai进程无法关闭，复现了一下，发现引起的原因有电脑用bot号发信息有关

**Comment by damemod** [comment]
> > 【未知的错误】不知道怎么回事，不影响使用的话可以先凑合着用
> > 闪照转发权限问题已修复，可以下载[1.0.3](https://github.com/MX233/AntiRecall/releases/download/1.0.3/antiRecall-1.0.3.mirai.jar)版本使用
> 
> 会使mirai进程无法关闭，复现了一下，发现引起的原因有用电脑用bot号发信息有关
